// You can insert code here by setting file_header_inc in file common.tpl

//=============================================================================
// Project  : generated_tb
//
// File Name: write_monitor.sv
//
//
// Version:   1.0
//
// Code created by Easier UVM Code Generator version 2016-04-18-EP on Sat Mar 14 15:57:18 2026
//=============================================================================
// Description: Monitor for write
//=============================================================================

`ifndef WRITE_MONITOR_SV
`define WRITE_MONITOR_SV

// You can insert code here by setting monitor_inc_before_class in file write_agent.tpl

class write_monitor extends uvm_monitor;

  `uvm_component_utils(write_monitor)

  virtual write_if vif;

  uvm_analysis_port #(write_trans) analysis_port;

  write_trans m_trans;

  extern function new(string name, uvm_component parent);

  // Methods build_phase, run_phase, and do_mon generated by setting monitor_inc in file write_agent.tpl
  extern function void build_phase(uvm_phase phase);
  extern task run_phase(uvm_phase phase);
  extern task do_mon();

  // You can insert code here by setting monitor_inc_inside_class in file write_agent.tpl

endclass : write_monitor 


function write_monitor::new(string name, uvm_component parent);
  super.new(name, parent);
  analysis_port = new("analysis_port", this);
endfunction : new


function void write_monitor::build_phase(uvm_phase phase);
endfunction : build_phase


task write_monitor::run_phase(uvm_phase phase);
  `uvm_info(get_type_name(), "run_phase", UVM_HIGH)

  m_trans = write_trans::type_id::create("m_trans");
  do_mon();
endtask : run_phase


// Start of inlined include file generated_tb/tb/include/write_monitor_inc.sv
task write_monitor::do_mon();

  forever begin
    @(posedge vif.write_clk);

    if (vif.wr_en && !vif.full) begin
        m_trans.data = vif.data_in;

        `uvm_info("WRITE_MON",
           $sformatf("WRITE data = %0h", vif.data_in),
           UVM_LOW)

        analysis_port.write(m_trans);
    end

  end

endtask// End of inlined include file

// You can insert code here by setting monitor_inc_after_class in file write_agent.tpl

`endif // WRITE_MONITOR_SV

