// You can insert code here by setting file_header_inc in file common.tpl

//=============================================================================
// Project  : generated_tb
//
// File Name: write_driver.sv
//
//
// Version:   1.0
//
// Code created by Easier UVM Code Generator version 2016-04-18-EP on Sat Mar 14 15:57:18 2026
//=============================================================================
// Description: Driver for write
//=============================================================================

`ifndef WRITE_DRIVER_SV
`define WRITE_DRIVER_SV

// You can insert code here by setting driver_inc_before_class in file write_agent.tpl

class write_driver extends uvm_driver #(write_trans);

  `uvm_component_utils(write_driver)

  virtual write_if vif;

  extern function new(string name, uvm_component parent);

  // Methods run_phase and do_drive generated by setting driver_inc in file write_agent.tpl
  extern task run_phase(uvm_phase phase);
  extern task do_drive();

  // You can insert code here by setting driver_inc_inside_class in file write_agent.tpl

endclass : write_driver 


function write_driver::new(string name, uvm_component parent);
  super.new(name, parent);
endfunction : new


task write_driver::run_phase(uvm_phase phase);
  `uvm_info(get_type_name(), "run_phase", UVM_HIGH)

  forever
  begin
    seq_item_port.get_next_item(req);
      `uvm_info(get_type_name(), {"req item\n",req.sprint}, UVM_HIGH)
    do_drive();
    seq_item_port.item_done();
  end
endtask : run_phase


// Start of inlined include file generated_tb/tb/include/write_driver_inc.sv
static bit first = 1;

task write_driver::do_drive();

  if (first) begin
    @(posedge vif.write_clk);
    vif.rst <= 1;

    repeat (5) @(posedge vif.write_clk);

    vif.rst <= 0;

    repeat (5) @(posedge vif.write_clk);

    first = 0;
  end

  // Wait until reset finished
  wait(!vif.rst);

  // Drive transaction
  vif.data_in <= req.data;

  @(posedge vif.write_clk);
  vif.wr_en <= 1;

  `uvm_info("WRITE_DRV",
  $sformatf("WRITE: data=%0d full=%0b", req.data, vif.full),
  UVM_MEDIUM)

  @(posedge vif.write_clk);
  vif.wr_en <= 0;

endtask// End of inlined include file

// You can insert code here by setting driver_inc_after_class in file write_agent.tpl

`endif // WRITE_DRIVER_SV

