// You can insert code here by setting file_header_inc in file common.tpl

//=============================================================================
// Project  : generated_tb
//
// File Name: read_driver.sv
//
//
// Version:   1.0
//
// Code created by Easier UVM Code Generator version 2016-04-18-EP on Sat Mar 14 15:57:18 2026
//=============================================================================
// Description: Driver for read
//=============================================================================

`ifndef READ_DRIVER_SV
`define READ_DRIVER_SV

// You can insert code here by setting driver_inc_before_class in file read_agent.tpl

class read_driver extends uvm_driver #(read_trans);

  `uvm_component_utils(read_driver)

  virtual read_if vif;

  extern function new(string name, uvm_component parent);

  // Methods run_phase and do_drive generated by setting driver_inc in file read_agent.tpl
  extern task run_phase(uvm_phase phase);
  extern task do_drive();

  // You can insert code here by setting driver_inc_inside_class in file read_agent.tpl

endclass : read_driver 


function read_driver::new(string name, uvm_component parent);
  super.new(name, parent);
endfunction : new


task read_driver::run_phase(uvm_phase phase);
  `uvm_info(get_type_name(), "run_phase", UVM_HIGH)

  forever
  begin
    seq_item_port.get_next_item(req);
      `uvm_info(get_type_name(), {"req item\n",req.sprint}, UVM_HIGH)
    do_drive();
    seq_item_port.item_done();
  end
endtask : run_phase


// Start of inlined include file generated_tb/tb/include/read_driver_inc.sv
task read_driver::do_drive();

  @(posedge vif.read_clk);

  if (!vif.empty) begin
    vif.rd_en <= 1;
    @(posedge vif.read_clk);
    vif.rd_en <= 0;
  end

endtask
// End of inlined include file

// You can insert code here by setting driver_inc_after_class in file read_agent.tpl

`endif // READ_DRIVER_SV

