// You can insert code here by setting file_header_inc in file common.tpl

//=============================================================================
// Project  : generated_tb
//
// File Name: read_monitor.sv
//
//
// Version:   1.0
//
// Code created by Easier UVM Code Generator version 2016-04-18-EP on Sat Mar 14 15:57:18 2026
//=============================================================================
// Description: Monitor for read
//=============================================================================

`ifndef READ_MONITOR_SV
`define READ_MONITOR_SV

// You can insert code here by setting monitor_inc_before_class in file read_agent.tpl

class read_monitor extends uvm_monitor;

  `uvm_component_utils(read_monitor)

  virtual read_if vif;

  uvm_analysis_port #(read_trans) analysis_port;

  read_trans m_trans;

  extern function new(string name, uvm_component parent);

  // Methods build_phase, run_phase, and do_mon generated by setting monitor_inc in file read_agent.tpl
  extern function void build_phase(uvm_phase phase);
  extern task run_phase(uvm_phase phase);
  extern task do_mon();

  // You can insert code here by setting monitor_inc_inside_class in file read_agent.tpl

endclass : read_monitor 


function read_monitor::new(string name, uvm_component parent);
  super.new(name, parent);
  analysis_port = new("analysis_port", this);
endfunction : new


function void read_monitor::build_phase(uvm_phase phase);
endfunction : build_phase


task read_monitor::run_phase(uvm_phase phase);
  `uvm_info(get_type_name(), "run_phase", UVM_HIGH)

  m_trans = read_trans::type_id::create("m_trans");
  do_mon();
endtask : run_phase


// Start of inlined include file generated_tb/tb/include/read_monitor_inc.sv
task read_monitor::do_mon();

  forever begin
    @(posedge vif.read_clk);

    if (vif.rd_valid) begin

      m_trans.data = vif.data_out;

      `uvm_info("READ_MON",
      $sformatf("READ DATA %0d empty=%0b", vif.data_out, vif.empty),
      UVM_MEDIUM)

      analysis_port.write(m_trans);

    end

  end

endtask// End of inlined include file

// You can insert code here by setting monitor_inc_after_class in file read_agent.tpl

`endif // READ_MONITOR_SV

